replicaCount: 1

image:
  repository: ghcr.io/snapp-incubator/jira-msteams-proxy
  pullPolicy: Always
  tag: "v0.9"

service:
  port: 8080

route:
  enabled: false
httpproxy:
  enabled: true

resources:
  limits:
    memory: 500Mi
    cpu: 500m
  requests:
    memory: 500Mi
    cpu: 300m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
