replicaCount: 1

image:
  repository: ghcr.io/snapp-incubator/jira-element-proxy
  pullPolicy: Always
  tag: "main@sha256:afb77917d7186242ace86974cc7276974a2d3efb98dd90462b1614902a085bdf"

service:
  port: 8080

resources:
  limits:
    memory: 500Mi
    cpu: 500m
  requests:
    memory: 500Mi
    cpu: 300m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
