{{- if .Values.httpproxy.enabled -}}
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jira-webhook-proxy
spec:
  httpVersions:
  - http/1.1
  ingressClassName: private
  routes:
  - enableWebsockets: true
    loadBalancerPolicy:
      strategy: RoundRobin
    services:
    - name: jira-webhook-proxy
      port: {{ .Values.service.port }}
      weight: 100
    timeoutPolicy:
      idleConnection: 15s
      response: 30s
  virtualhost:
    fqdn: jira-webhook-proxy.apps.private.{{ .Values.region_hostname }}
    tls:
      enableFallbackCertificate: true
      secretName: openshift-ingress/letsencrypt
{{- end }}
